"""Generate and write the daily brief to the Obsidian vault."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from sqlmodel import Session

from lifeos.config import Settings, get_settings
from lifeos.ingestion.obsidian.writeback import write_managed_block
from lifeos.services.plan import plan_and_persist
from lifeos.services.sync import resolve_vault_path


@dataclass
class BriefResult:
    path: Path
    content: str
    written: bool


def generate_brief_markdown(session: Session, *, now: datetime | None = None) -> str:
    """Build the daily brief markdown body (inside managed block)."""
    reference = now or datetime.now()
    plan = plan_and_persist(session, now=reference, persist=False)
    rec = plan.recommendation

    lines = ["## 🎯 Today's Plan (generated by LifeOS)", ""]

    if rec.top_pick:
        lines.append(
            f"**Recommended next:** {rec.top_pick.title} "
            f"(score {rec.top_pick.score:.2f})"
        )
        lines.append("")

    if plan.blocks:
        lines.append("### Schedule")
        for block in plan.blocks:
            start = block.start.strftime("%H:%M")
            end = block.end.strftime("%H:%M")
            lines.append(f"- {start}–{end} · {block.title} — {block.rationale}")
        lines.append("")

    if plan.conflicts:
        lines.append("### ⚠️ Conflicts")
        for conflict in plan.conflicts:
            lines.append(f"- {conflict.message}")
        lines.append("")

    if rec.ranked:
        lines.append("### Ranked priorities")
        for i, item in enumerate(rec.ranked[:5], start=1):
            lines.append(f"{i}. {item.title} ({item.score:.2f})")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_daily_brief(
    session: Session,
    *,
    now: datetime | None = None,
    settings: Settings | None = None,
    dry_run: bool = False,
) -> BriefResult:
    """Write (or preview) the daily brief into today's daily note."""
    cfg = settings or get_settings()
    vault = resolve_vault_path(cfg)
    reference = now or datetime.now()
    subdir = cfg.daily_notes_subdir
    note_path = vault / subdir / f"{reference.strftime('%Y-%m-%d')}.md"

    body = generate_brief_markdown(session, now=reference)
    if dry_run:
        return BriefResult(path=note_path, content=body, written=False)

    _ensure_daily_note(note_path, reference, cfg)
    write_managed_block(note_path, block_id="daily-brief", content=body)
    return BriefResult(path=note_path, content=body, written=True)


def _ensure_daily_note(path: Path, day: datetime, settings: Settings) -> None:
    if path.exists():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    header = f"# {day.strftime('%A, %B %d %Y')}\n\n"
    path.write_text(header, encoding="utf-8")
