"""Weekly review generation and vault writeback."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime, time, timedelta
from pathlib import Path

from sqlmodel import Session

from lifeos.config import Settings, get_settings
from lifeos.engine.balance import compute_actual_allocations, compute_balance_drift
from lifeos.engine.velocity import flag_goal_velocity
from lifeos.ingestion.obsidian.writeback import write_managed_block
from lifeos.models.weekly_review import WeeklyReviewCreate
from lifeos.repositories import (
    CalibrationRepository,
    CompletionLogRepository,
    WeeklyReviewRepository,
)
from lifeos.schemas.snapshot import CompletionLogSnapshot
from lifeos.services.recommend import build_snapshot
from lifeos.services.sync import resolve_vault_path


@dataclass
class ReviewResult:
    path: Path
    content: str
    written: bool
    week_start: date


def week_start_for(day: date | None = None) -> date:
    """Monday of the week containing ``day`` (or today)."""
    reference = day or date.today()
    return reference - timedelta(days=reference.weekday())


def generate_review_markdown(
    session: Session,
    *,
    week_start: date,
) -> tuple[str, WeeklyReviewCreate]:
    """Build weekly review body and structured record."""
    week_end = week_start + timedelta(days=6)
    reference = datetime.combine(week_end, time(23, 59, 59))
    snapshot = build_snapshot(session, now=reference)

    week_logs = CompletionLogRepository(session).list_for_week(week_start)
    completions = [_completion_snapshot(log) for log in week_logs]

    actual = compute_actual_allocations(completions)
    targets = {area_id: area.target_allocation for area_id, area in snapshot.areas.items()}
    drift = compute_balance_drift(target_allocations=targets, actual_allocations=actual)

    goal_flags = flag_goal_velocity(snapshot.goals, completions, now=reference)
    cal_repo = CalibrationRepository(session)
    factors = {f.area_id: f for f in cal_repo.list_all(limit=100)}

    total_estimated = sum(log.estimated_minutes for log in week_logs)
    total_actual = sum(log.actual_minutes for log in week_logs)
    accuracy = total_actual / total_estimated if total_estimated else 1.0

    by_area: dict[str, float] = _area_hours(week_logs, snapshot.areas)
    planned_vs_actual = {
        "week_start": week_start.isoformat(),
        "estimated_minutes": total_estimated,
        "actual_minutes": total_actual,
        "accuracy_ratio": round(accuracy, 2),
        "by_area": by_area,
    }
    goal_progress = {
        str(g.id): {
            "title": g.title,
            "progress": g.progress,
            "target_date": g.target_date.isoformat() if g.target_date else None,
        }
        for g in snapshot.goals.values()
    }

    lines = [
        f"## Weekly review — {week_start.isoformat()} → {week_end.isoformat()}",
        "",
        f"_Generated by LifeOS · {total_actual} min completed "
        f"(est {total_estimated} min, accuracy {accuracy:.0%})_",
        "",
        "### Time by area",
    ]
    for area_id, area in sorted(snapshot.areas.items(), key=lambda x: x[1].key):
        hours = by_area.get(area.key, 0.0)
        target_pct = area.target_allocation * 100
        actual_pct = actual.get(area_id, 0.0) * 100
        drift_val = drift.get(area_id, 0.0)
        flag = ""
        if drift_val > 0.08:
            flag = " ⚠️ underserved"
        lines.append(
            f"- **{area.key}**: {hours:.1f}h "
            f"(target {target_pct:.0f}%, actual {actual_pct:.0f}%){flag}"
        )
    lines.append("")

    if factors:
        lines.append("### Estimation calibration")
        for factor in sorted(factors.values(), key=lambda f: (f.area_id is None, f.area_id or 0)):
            label = "global" if factor.area_id is None else _area_name(factor.area_id, snapshot)
            lines.append(
                f"- {label}: **{factor.ratio:.2f}×** "
                f"({factor.sample_count} sample(s))"
            )
        lines.append("")

    if goal_flags:
        lines.append("### Goal health")
        for goal_flag in goal_flags:
            lines.append(
                f"- **{goal_flag.title}** ({goal_flag.kind}): {goal_flag.message}"
            )
        lines.append("")

    if week_logs:
        lines.append("### Completed tasks")
        for log in week_logs[:20]:
            delta = log.actual_minutes - log.estimated_minutes
            sign = "+" if delta >= 0 else ""
            lines.append(
                f"- {log.title}: {log.actual_minutes} min "
                f"(est {log.estimated_minutes}, {sign}{delta} min)"
            )
        if len(week_logs) > 20:
            lines.append(f"- _…and {len(week_logs) - 20} more_")
        lines.append("")

    lines.extend(
        [
            "### Wins",
            "",
            "### Misses",
            "",
            "### Blockers",
            "",
            "### Next week focus",
            "",
        ]
    )

    body = "\n".join(lines).rstrip() + "\n"

    from lifeos.ai.client import synthesize_review_narrative

    narrative = synthesize_review_narrative(body)
    if narrative:
        body = body + f"\n### AI summary\n\n{narrative}\n"

    record = WeeklyReviewCreate(
        week_start=week_start,
        planned_vs_actual=planned_vs_actual,
        goal_progress=goal_progress,
        energy_summary={},
        generated_summary=body,
    )
    return body, record


def write_weekly_review(
    session: Session,
    *,
    week_start: date | None = None,
    settings: Settings | None = None,
    dry_run: bool = False,
) -> ReviewResult:
    """Write (or preview) the weekly review into the Obsidian vault."""
    cfg = settings or get_settings()
    vault = resolve_vault_path(cfg)
    start = week_start or week_start_for()
    subdir = cfg.weekly_reviews_subdir
    note_path = vault / subdir / f"weekly-{start.isoformat()}.md"

    body, record = generate_review_markdown(session, week_start=start)
    record.source_ref = str(note_path)

    if not dry_run:
        WeeklyReviewRepository(session).upsert(record)
        _ensure_review_note(note_path, start, body)
        write_managed_block(note_path, block_id="weekly-review", content=body)

    return ReviewResult(path=note_path, content=body, written=not dry_run, week_start=start)


def _ensure_review_note(path: Path, week_start: date, body: str) -> None:
    if path.exists():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    week_end = week_start + timedelta(days=6)
    header = (
        "---\n"
        f"type: weekly-review\n"
        f"week_start: {week_start.isoformat()}\n"
        "---\n\n"
        f"# Weekly review — {week_start.isoformat()} → {week_end.isoformat()}\n\n"
    )
    path.write_text(header, encoding="utf-8")


def _completion_snapshot(log) -> CompletionLogSnapshot:
    return CompletionLogSnapshot(
        task_id=log.task_id,
        area_id=log.area_id,
        goal_id=log.goal_id,
        estimated_minutes=log.estimated_minutes,
        actual_minutes=log.actual_minutes,
        completed_at=log.completed_at.replace(tzinfo=None)
        if log.completed_at.tzinfo
        else log.completed_at,
    )


def _area_hours(logs, areas) -> dict[str, float]:
    by_key: dict[str, int] = {}
    id_to_key = {a.id: a.key for a in areas.values()}
    for log in logs:
        if log.area_id is None:
            continue
        key = id_to_key.get(log.area_id, str(log.area_id))
        by_key[key] = by_key.get(key, 0) + log.actual_minutes
    return {key: minutes / 60.0 for key, minutes in by_key.items()}


def _area_name(area_id: int, snapshot) -> str:
    area = snapshot.areas.get(area_id)
    return area.key if area else str(area_id)
